# Generated by Django 2.1.5 on 2019-05-09 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.DecimalField(decimal_places=2, max_digits=4)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='edge',
            name='end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end', to='home.Job'),
        ),
        migrations.AddField(
            model_name='edge',
            name='start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start', to='home.Job'),
        ),
    ]
